// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sqfceaibwygfavqbmtxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZmNlYWlid3lnZmF2cWJtdHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MjcxMjUsImV4cCI6MjA4OTIwMzEyNX0.ovQcCxMMNLSTyrQv9vLWxQ0kNhh2Qo5-RKjS7Iwtdrw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);